### ISSUE TITLE
Correct naming

### ISSUE THREAD

**Issue by sarthak-sehgal** [Akshit-Patel/frontend-101#13]
@Akshit-Patel please follow the directory structure and naming given in the general instructions. The folders ahould be named "A" and "B" with tasks named "1.html", etc.

**Comment by Akshit-Patel** [comment]
I am trying to rename and move files with git mv command but its deleting attached history with files . I will try to do it and update remote repository

**Comment by Akshit-Patel** [comment]
Files were correctly renamed
